<?php

/**
 * @file
 * Custom blocks for the Live With the Sea website.
 */

function lwts_custom_blocks_block_info() {

  $blocks['topic-nav'] = array (
    'info' => 'LWtS Topic navigation',
  );
  $blocks['related-articles'] = array (
    'info' => 'LWtS Related articles',
  );

  return $blocks;
}

function lwts_custom_blocks_block_view( $delta = '' ) {

  switch ( $delta ) {
  case 'topic-nav' :
    $block['content'] = _lwts_custom_blocks_topic_nav_content();
    return $block;
  case 'related-articles' :
    $block['subject'] = t( 'Related articles' );
    $block['content'] = _lwts_custom_blocks_related_articles_content();
    return $block;
  }
}

function _lwts_custom_blocks_topic_nav_content() {

  // HACK - hard coded relevant vocabulary id.
  $topics_vid = 3;

  // Get the top level Topic terms
  $top_level_terms = taxonomy_get_tree( $topics_vid, 0, 1 );

  // For the first taxonomy branch: In order to add a CSS class.
  $first = TRUE;

  $result = '';

  foreach ( $top_level_terms as $top_level_term ) {

    if ( $first ) {
      $result .= '<div class="taxonomy-branch first">';
      $first = FALSE;
    }
    else {
      $result .= '<div class="taxonomy-branch">';
    }

    $result .= '<div class="top-level-topic">';
    $result .=
      l( $top_level_term->name, 'taxonomy/term/' . $top_level_term->tid );
    $result .= '</div><br/>';

    // Only fetch the next level of terms. Don't fetch third and lower
    // levels of terms.
    $sub_terms = taxonomy_get_tree(
      $top_level_term->vid, $top_level_term->tid, 1 );

    if ( empty( $sub_terms ) ) {
      $result .= '<div class="sub-topics empty"></div>';
    }
    else {
      $result .= '<div class="sub-topics"/>';
      foreach ( $sub_terms as $sub_term ) {
        $result .= '<div class="sub-topic"/>' .
          l( $sub_term->name, 'taxonomy/term/' . $sub_term->tid ) .
          '</div>';
      }
      $result .= '</div>';
    }

    $result .= '</div>';
  }

  $result .= '<div class="clearfix"></div>';
  return $result;
}

function _lwts_custom_blocks_related_articles_content() {

  if ( arg(0) != 'node' || !is_numeric( arg(1) ) ) {
    return;
  }

  $node_id = arg(1);
  $node = node_load( $node_id );
  $term_ids = _lwts_custom_blocks_get_term_ids_from_node_id( $node_id );

  // @todo Using all terms, including Knowledge Type terms, for now.
  // Customer may want us to refine this.
  $terms_string = implode( $term_ids, '+' );

  return views_embed_view( 'related_articles', 'default', $terms_string );
}

function _lwts_custom_blocks_get_term_ids_from_node_id( $node_id ) {

  $query = db_select( 'taxonomy_index', 'ti' );
  $query->addField( 'ti', 'tid', 'tid' );
  $query->condition( 'ti.nid', $node_id, '=' );

  $result_set =  $query->execute();
  $term_ids = $result_set->fetchCol();

  //dsm( $term_ids );

  return $term_ids;
}

