<?php

/**
 * @file
 * Pages specific to LWtS that were prohibitively difficult to do using
 * the Panels module.
 */

// GENERICISE LATER!!!! Don't be trapped in to making very generic fns first

/**
 * Implements hook_menu()
 */
function lwts_custom_pages_menu() {

  $items = array();

  // Home page
  $items['home-page'] = array (
    'title' => 'Home',
    'description' => 'See the latest from Live with the Sea',
    'page callback' => 'lwts_custom_pages_home_page',
  );

  return $items;
}

/**
 * Page callback for the home page.
 */
function lwts_custom_pages_home_page() {

  // No need for a primary topic field when done this way!!!!!

  // Admin vars:
  $sort_property = 'changed';
  $sort_order = 'DESC';
  $is_sticky_applies = TRUE;
  $prime_vocab = 'Knowledge type';
  $second_vocab = 'Topic';
  $max_columns = 3;

  // Get all nodes of types (article, video), ordered by <sort order> and
  // grouped by stickiness if <sticky applies>.
  $nodes = _lwts_custom_pages_get_nodes(
    $sort_property,
    $sort_order,
    $is_sticky_applies,
    $prime_vocab,
    $second_vocab,
    $max_columns
  );

  //
  // For each term in the <primary vocab>
  //   remove the first node that is tagged with that term.
  //   output teaser for removed node
  //
  // For each term in the <secondary vocab>
  //   ditto
  //
}

// HOOK_???? When taxonomy term added or removed from primary or secondary
//      vocab - recalculate column widths - css
//
// Admin settings form. When max columns changes - recalc col widths - css
