<?php
// $Id: permission_select.module,v 1.1.4.2 2009/05/18 00:29:20 himerus Exp $
/**
 * @file
 * Module will add select all/deselect all options through out the 
 * admin permission selection screen
 */

/**
 * Implementation of hook_perm().
 */
function permission_select_perm() {
  return array(
    'use permission select' => array(
      'title' => t('Use permission select'),
      'description' => t('Adds a check all / uncheck all option to each role/module pair on the permissions page.'),
    ),
  );
}
/**
 * Implementation of hook_init().
 */
function permission_select_init() {
  if (user_access('use permission select') && 
substr($_GET['q'], 0, 22) == 'admin/user/permissions') {
    $path = drupal_get_path('module', 'permission_select');
    drupal_add_css($path .'/permission_select.css', array('type' => 'module', 'media' => 'all', 'preprocess' => TRUE,));
    drupal_add_js($path .'/permission_select.js');
  }
}
/**
 * hook_theme_registry_alter
 * telling the system we want to use out custom function to render this form
 */
function permission_select_theme_registry_alter(&$theme_registry) {
  if (!empty($theme_registry['user_admin_perm'])) {
    $theme_registry['user_admin_perm']['function'] = 'permission_select_theme_user_admin_perm';
  }
}
/**
 * Theme the administer permissions page.
 */
function permission_select_theme_user_admin_perm($form) {
  $roles = user_roles();
  foreach (element_children($form['permission']) as $key) {
    // Don't take form control structures
    if (is_array($form['permission'][$key])) {
      $row = array();
      // Module name
      if (is_numeric($key)) {
        $mod_name = t($form['permission'][$key]['#id']);
        $row[] = array('data' => t('@module module', array('@module' => drupal_render($form['permission'][$key]))), 'class' => 'module module_name', 'id' => 'module-'. $mod_name, 'colspan' => count($form['role_names']) + 1);
      }
      else {
        // Permission row.
        $row[] = array(
          'data' => drupal_render($form['permission'][$key]),
          'class' => 'permission',
        );
        foreach (element_children($form['checkboxes']) as $rid) {
          if (is_array($form['checkboxes'][$rid])) {
            $row[] = array('data' => drupal_render($form['checkboxes'][$rid][$key]), 'class' => 'checkbox module-'. $mod_name, 'title' => $roles[$rid] . ' : ' . t($key));
          }
        }
      }
      $rows[] = array(
        'data' => $row,
        'class' => 'module-'. $mod_name,
      );
    }
  }
  $header[] = (t('Permission'));
  foreach (element_children($form['role_names']) as $rid) {
    if (is_array($form['role_names'][$rid])) {
      $header[] = array('data' => drupal_render($form['role_names'][$rid]), 'class' => 'checkbox');
    }
  }
  $output = theme('system_compact_link');
  $output .= theme('table', $header, $rows, array('id' => 'permissions'));
  $output .= drupal_render_children($form);
  return $output;
}






function _____theme_user_admin_perm($form) {
  $roles = user_roles();
  foreach (element_children($form['permission']) as $key) {
    // Don't take form control structures
    if (is_array($form['permission'][$key])) {
      $row = array();
      // Module name
      if (is_numeric($key)) {
        $row[] = array('data' => drupal_render($form['permission'][$key]), 'class' => 'module', 'id' => 'module-' . $form['permission'][$key]['#id'], 'colspan' => count($form['role_names']) + 1);
      }
      else {
        // Permission row.
        $row[] = array(
          'data' => drupal_render($form['permission'][$key]),
          'class' => 'permission',
        );
        foreach (element_children($form['checkboxes']) as $rid) {
          if (is_array($form['checkboxes'][$rid])) {
            $row[] = array('data' => drupal_render($form['checkboxes'][$rid][$key]), 'class' => 'checkbox', 'title' => $roles[$rid] . ' : ' . t($key));
          }
        }
      }
      $rows[] = $row;
    }
  }
  $header[] = (t('Permission'));
  foreach (element_children($form['role_names']) as $rid) {
    if (is_array($form['role_names'][$rid])) {
      $header[] = array('data' => drupal_render($form['role_names'][$rid]), 'class' => 'checkbox');
    }
  }
  $output = theme('system_compact_link');
  $output .= theme('table', $header, $rows, array('id' => 'permissions'));
  $output .= drupal_render_children($form);
  return $output;
}
